### ISSUE TITLE
SQL tab disabled using Castle.ActiveRecord

### ISSUE THREAD

**Issue by rodrigojuarez** [stevenlauwers22/Glimpse.NHibernate#1]
I don't see any information logged in SQL Tab.
I'm using Castle.ActiveRecord.
This Glimpe plugin should work anyway?
Any directions about how can I debug the problem?

**Comment by stevenlauwers22** [comment]
@rodrigojuarez is you're code publicly available? Which version of NHibernate are you using?

**Comment by rodrigojuarez** [comment]
The code it's not publicly available, I'm using NHibernate 3.0.0.4000 and Castle.ActiveRecord 3.0.0.130
I will create a test project to try to reproduce the problem with the latest packages from nuget

**Comment by rodrigojuarez** [comment]
@stevenlauwers22 I just created a test project https://github.com/rodrigojuarez/GlimpseNHibernateTestAR

**Comment by stevenlauwers22** [comment]
@rodrigojuarez great! I'll try to check it out asap (probably tomorrow).

**Comment by stevenlauwers22** [comment]
The error logs show the following:
2015-02-26 15:49:25.6846 | INFO | NHibernateInspector: Started wrapping the NHibernate DbDriver | 
2015-02-26 15:49:25.6846 | INFO | NHibernateInspector: Found 0 drivers to wrap | 
2015-02-26 15:49:25.6846 | INFO | NHibernateInspector: Finished wrapping the NHibernate DbDriver | 

Will continue investigation later today.

**Comment by stevenlauwers22** [comment]
Got it working by using a hack :)

2015-02-26 15:57:03.5679 | INFO | NHibernateInspector: Started wrapping the NHibernate DbDriver | 
2015-02-26 15:57:03.5679 | INFO | NHibernateInspector: Found 1 drivers to wrap | 
2015-02-26 15:57:03.7109 | INFO | NHibernateInspector: Wrapped a driver ... 
Original driver type: NHibernate.Driver.SqlClientDriver
Glimpse driver type: Glimpse.NHibernate.AlternateType.GlimpseDbDriverNh3004000 | 
2015-02-26 15:57:03.7109 | INFO | NHibernateInspector: Finished wrapping the NHibernate DbDriver | 

The problem is that the NHibernate SessionFactory has not been created yet at the time my Glimpse plugin is initialized. Therefore I can't find any SQL drivers to wrap.
It works if it put the following in the application_start of your global.asax: Names.FindAll();

There might be a better way to get ActiveRecord to created the session factory, but I'm not familiar with this library.

If you have any better ideas to get this working, feel free to get back at me!

Cheers,

Steven

**Comment by rodrigojuarez** [comment]
Hi

Thanks for the update! All working!
I do not think it's a problem applying the hack you found
I have the same problem with other ORM, that I need to access some date before the initialization occurs.
Maybe adding an optional manual configuration step could be more clear?

Thanks a lot!
